platform :ios, '8.0'
use_frameworks!
def pods
pod "SnapKit"
pod "SDWebImage"
pod "TYAlertController"
pod "SVProgressHUD"
pod "FMDB"
pod "MJRefresh"
pod 'YYKit'
pod "PromiseKit", "~> 3.2"
pod 'AFNetworking', '~> 3.0'
pod 'ObjectMapper'
pod 'Reusable'
pod 'Alamofire'
pod 'JSQMessagesViewController'

end
target 'TestYYKit' do
pods
end