
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
def pods
pod 'SnapKit'
pod "SDWebImage"
pod "TYAlertController"
pod "SVProgressHUD"
pod "FMDB"
pod "MJRefresh"
pod "PromiseKit", "~> 3.2"
pod 'AFNetworking', '~> 3.0'
pod 'Reusable'
pod 'JSQMessagesViewController'
pod 'YYText'
pod 'CocoaAsyncSocket'
pod 'SKPhotoBrowser'
pod "ElasticTransition", "~> 3.0.0"

end
target 'TestYYKit' do
pods
end